#include <iostream>
#include <fstream>
#include <unistd.h>
#include <chrono>
#include <ncurses.h>
#include <string>
#include "player.h"
#include "cli.h"
#include "database.h"
#include "menu_choice.h"
#include "engine.h"